spring:
  jpa:
    hibernate:
      dll-auto: update
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/db?autoReconnect=true&useSSL=false}
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    producer:
      bootstrap-servers: ${SPRING_BOOTSTRAP_URL:localhost:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
topic:
  people-created: people-created

loggin:
  level:
    root: INFO
